# Generated by Django 5.0.4 on 2024-04-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('art', models.ImageField(blank=True, null=True, upload_to='galeria/img/')),
            ],
        ),
    ]
