# Generated by Django 5.0.4 on 2024-04-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='art',
        ),
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('art', models.ImageField(blank=True, null=True, upload_to='galeria/img/')),
                ('nome_artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nome_artista', to='galeria.artista')),
            ],
        ),
    ]
