# Generated by Django 5.0.4 on 2024-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_remove_artista_art_arte'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
